.eslintrc.json, src/components/Admin/AuthenticatedAdmin.tsx, src/components/Admin/Authentication/SignIn.tsx, src/components/Admin/Authentication/SignOut.tsx, src/components/Admin/Authentication/SignUp.tsx, src/components/Admin/Authentication/Util.tsx, src/contexts/AuthContext.tsx, src/pages/Admin.tsx
This PR includes the code from the skeleton PR, so review that PR first and then I'll merge so it's clear what changes are new in this PR.
=> Implement Google Authentication: Admin Set Up #2

src/components/Admin/Authentication/SignIn.tsx, src/components/Admin/Authentication/SignUp.tsx, src/components/Admin/Authentication/Util.tsx, src/pages/Admin.tsx
This PR builds off of the email-auth PR. After that PR is approved, I'll merge so that the changes made in this PR are more apparent.
=> Implement Email Authentication: Admin Set Up #3

.github/workflows/deploy.yml, .github/workflows/node.js.yml
=> Change all references from master branch to main branch

src/contexts/AuthContext.tsx
This fixes the issue that upon sign out, a user is rerouted to the sign in page
=> Fix authentication status variable bug

functions/src/aqi-calculation/calculate-aqi.ts
Oops, a few minutes of our data has the wrong location
=> Fix lat bug

firestore.rules
So all users can see the graph.
=> Allows sensor doc reads for all

public/locales/es/home.json
We merged collapsible UI before the translation reviews to make our development process easier for other projects. Now I'm addressing those changes.
=> Addressed Hillary's translation review

.eslintrc.json, public/locales/en/home.json, public/locales/es/home.json, src/components/AqiGauge/AqiDial.tsx, src/components/AqiGauge/GaugeSvg.tsx, src/components/AqiGraph/AqiGraph.tsx, src/components/Map/Map.tsx, src/components/Map/markerStyle.tsx, src/components/Util/Colors.tsx, src/contexts/AppProviders.tsx, src/contexts/ColorContext.tsx, src/pages/Home.tsx, src/util.tsx
Also removes construction notice, implements heading, and externalizes cutoff values.
=> Implement color accessibility features

src/contexts/AuthContext.tsx
This should fix the bug to create a new user document for a new user
=> Switch update to set to allow new document to be created

functions/src/index.ts
I've been really bad and mistook the field name and because that part is dynamic, none of the type checkers could catch me  (just another reason we made the right decision to use a type checker everywhere else 😄)
=> Deletion Phase 0d: Access correct field of user document

functions/src/aqi-calculation/calculate-aqi.ts, functions/src/aqi-calculation/cleaned-reading.ts, functions/src/aqi-calculation/purple-air-response.ts
This moves the coefficient recalculation out of an if statement so that the coefficient is decreased for every hour (even if an hour does not have enough data).
I also added some comments and improved some database write code from when Amber and I were debugging.
This also removes an extraneous if-check for `isActive` since we now only get the docs that are active
=> Fix AQI Buffer Bug

firestore.rules
Need to be able to read to merge data
=> Allow admins to read deletion document

functions/.eslintrc.json, functions/src/delete-marked-readings.ts, functions/src/index.ts
Tested locally on a small sample set.
=> Deletion Phase 2: Actually delete marked data

src/components/Admin/Authentication/ForgotPassword.tsx, src/components/Admin/Authentication/SignIn.tsx, src/components/Admin/Authentication/SignUp.tsx, src/components/AqiGauge/AqiDial.tsx, src/components/AqiGauge/InvalidSensor.tsx, src/components/Health/AqiTable.tsx, src/components/Util/Colors.tsx, src/pages/About.tsx, src/pages/Health.tsx, src/pages/Page404.tsx
I added a `LinkColor` to the colors and used that for all the links on the site. Also made the links slightly darker, but if you have a different color preference feel free to text me the hex or change it yourself, I'm not attached to it.
=> Link Colors

public/locales/en/about.json, public/locales/es/about.json, src/pages/About.tsx
=> Added assembly bill 617 link

public/locales/en/about.json, public/locales/es/about.json, src/pages/About.tsx
=> Add GitHub blurb to about page

src/components/Admin/ManageAccount/ChangeName.tsx, src/components/Admin/ManageAccount/DeleteAccountPopover.tsx, src/components/Admin/ManageAccount/ManageAccount.tsx, src/contexts/AuthContext.tsx
This allows `googleUser` and `passwordUser` to be accessed more easily rather than passing the values between components
=> Convert google and password user to context

public/locales/en/about.json, public/locales/es/about.json, src/pages/About.tsx
=> added blurb about sensor locations to the about page

public/locales/es/common.json
I believe Liz had corrected my use of seguro in this context before
=> Change translation for safe to healthy in spanish

.eslintrc.json, public/locales/en/about.json, public/locales/es/about.json, src/pages/About.tsx
Closes #636 
Not much Spanish here, would you mind giving it a look over? If you feel confident enough I don't think we need to run it by Hillary.
=> Added download as app instructions to about page

package-lock.json, package.json
=> Removed react-gauge-charts package
